name: Run Workflow

on:
  push:
    branches:
      - master

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - uses: lint
      - uses: jest
      - run: echo 'MF'
